// Code generated by "stringer -type=RoundState"; DO NOT EDIT.

package xfundingv2

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PositionOpening-0]
	_ = x[PositionReady-1]
	_ = x[PositionClosing-2]
	_ = x[PositionClosed-3]
}

const _RoundState_name = "PositionOpeningPositionReadyPositionClosingPositionClosed"

var _RoundState_index = [...]uint8{0, 15, 28, 43, 57}

func (i RoundState) String() string {
	if i < 0 || i >= RoundState(len(_RoundState_index)-1) {
		return "RoundState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RoundState_name[_RoundState_index[i]:_RoundState_index[i+1]]
}
