// Code generated by "callbackgen -type HedgeSimulator"; DO NOT EDIT.

package grid2

import (
	"github.com/c9s/bbgo/pkg/types"
)

func (s *HedgeSimulator) OnTrade(cb func(trade types.Trade)) {
	s.tradeCallbacks = append(s.tradeCallbacks, cb)
}

func (s *HedgeSimulator) EmitTrade(trade types.Trade) {
	for _, cb := range s.tradeCallbacks {
		cb(trade)
	}
}
